// Copyright (C) 2022 The Android Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Changes from Qualcomm Technologies, Inc. are provided under the following license:
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

package vendor_selinux
var EXCEPTION_NO_FUZZER = []string{}
var (
   vendorServiceFuzzerBindings = map[string][]string{
    "vendor.qti.data.factoryservice.IFactory/default":                                   EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.display.color.IDisplayColor/default":                           EXCEPTION_NO_FUZZER,
    "android.hardware.neuralnetworks.IDevice/qti-default":                               EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.wifi.wifilearner.IWifiStats/default":                           EXCEPTION_NO_FUZZER,
    "vendor.qti.syshealthmon.ISysHealthMon/default":                                     EXCEPTION_NO_FUZZER,
    "vendor.qti.snapdragonServices.ISnapdragonServices/default":                         EXCEPTION_NO_FUZZER,
    "vendor.qti.qvirtvendor.IVendorVM/default":                                          EXCEPTION_NO_FUZZER,
    "com.qualcomm.qti.auth.securesampleauthdaemon":                                      EXCEPTION_NO_FUZZER,
    "com.qualcomm.qti.qseeproxysample":                                                  EXCEPTION_NO_FUZZER,
    "vendor.qti.diaghal.Idiag/default":                                                  EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.wifi.wifimyftm.IWifiMyFtm/default":                             EXCEPTION_NO_FUZZER,
    "vendor.qti.qepi.IQEPI/qepi":                                                        EXCEPTION_NO_FUZZER,
    "android.hardware.neuralnetworks.IDevice/qti-gpu":                                   EXCEPTION_NO_FUZZER,
    "android.hardware.neuralnetworks.IDevice/qti-dsp":                                   EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.radio.qtiradio.IQtiRadioStable/slot1":                          EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.radio.qtiradio.IQtiRadioStable/slot2":                          EXCEPTION_NO_FUZZER,
    "android.hardware.camera.provider.ICameraProvider/vendor.qti/0":                     EXCEPTION_NO_FUZZER,
    "android.hardware.drm.IDrmFactory/widevine":                                         EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.wifi.supplicant.ISupplicantVendor/default":                     EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.display.demura.IDemuraFileFinder/default":                      EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.camera.offlinecamera.IOfflineCameraService/default":            EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.camera.aon.IAONService/default":                                EXCEPTION_NO_FUZZER,
    "vendor.qti.ims.datachannelservice.IDataChannelService/default":                     EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.cacertaidlservice.IService/default":                            EXCEPTION_NO_FUZZER,
    "vendor.qti.ims.factoryaidlservice.IImsFactory/default":                             EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.data.iwlandata.IIWlan/slot1":                                   EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.data.iwlandata.IIWlan/slot2":                                   EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.agm.IAGM/default":                                              EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.agm.ICodecIpc/default":                                         []string{"agm_codec_ipc.aidl_fuzzer"},
    "vendor.nxp.nxpnfc_aidl.INxpNfc/default":                                            EXCEPTION_NO_FUZZER,
    "vendor.qti.MemHal.IMemHal/default":                                                 EXCEPTION_NO_FUZZER,
    "vendor.qti.data.ntn.IQmsSatelliteService/default":                                  EXCEPTION_NO_FUZZER,
    "vendor.qti.data.txpwrservice.ITxPwrService/default":                                EXCEPTION_NO_FUZZER,
    "vendor.qti.gnss.ILocAidlGnss/default":                                              EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.c2pa.IC2PA/default":                                            EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.capabilityconfigstore.ICapabilityConfigStore/default":          EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.pal.IPAL/default":                                              EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.qasr.IQasr/default":                                            EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.paleventnotifier.IPALEventNotifier/default":                    EXCEPTION_NO_FUZZER,
    "vendor.qti.ims.uceaidlservice.IUceService/default":                                 EXCEPTION_NO_FUZZER,
    "vendor.qti.ims.imscmaidlservice.IImsCmService/default":                             EXCEPTION_NO_FUZZER,
    "android.hardware.media.c2.IComponentStore/default2":                                EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.dsp.IDspService/default":                                       EXCEPTION_NO_FUZZER,
    "mapper/qti":                                                                        EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.dpmaidlservice.IDpmService/default":                            EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.mwqemadapteraidlservice.IMwqemAdapter/MwqemAdapter":            EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.qxr.IQXRCoreService/default":                                   EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.qxr.IQXRCamService/default":                                    EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.qxr.IQXRModService/default":                                    EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.qxr.IQXRCommService/default":                                   EXCEPTION_NO_FUZZER,
    "android.hardware.security.sharedsecret.ISharedSecret/strongbox":                    EXCEPTION_NO_FUZZER,
    "android.hardware.authsecret.qti.spu.IAuthSecret/default":                           EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.factory.IFactory/default":                                      EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.bluetooth_sar.IBluetoothSar/default":                           EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.fm.IFmHci/default":                                             EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.wifidisplaysession_aidl.IWifiDisplaySession/default":           EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.wifidisplaysession_aidl.IWifiDisplaySessionVideoTrack/default":                                   EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.wifidisplaysession_aidl.IWifiDisplaySessionAudioTrack/default":                                   EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.wifidisplaysession_aidl.IWifiDisplaySessionImageTrack/default":                                   EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.perf2.IPerf/default":                                           EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.hexlp.IHexlpService/default":                                   EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.hexlp.IHexlpService/unsigned":                                  []string{"aidl_fuzzer_hexlp_service"},
    "vendor.qti.hardware.power.powermodule.IPowerModule/default":                        EXCEPTION_NO_FUZZER,
    "vendor.qti.qhcp.IQHDC/default":                                                     EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.minkipcbinder.IMinkServer/default":                             EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.minkipcbinder.IMinkTransact/default":                           EXCEPTION_NO_FUZZER,
    "vendor.tsa.hdcp.IHDCPInterface/default":                                            EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.wifi.wificfr.IWificfr/default":                                 EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.soter.ISoter/default":                                          EXCEPTION_NO_FUZZER,
    "vendor.qti.memory.pasrmanager.IPasrManager/default":                                EXCEPTION_NO_FUZZER,
    "android.hardware.security.sharedsecret.ISharedSecret/gatekeeper":                   EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.bluetooth.btavsprovider.IBtAVsProvider/default":                []string{"vendor.qti.hardware.bluetooth.btavsprovider-aidl_fuzzer"},
    "vendor.qti.hardware.data.connectionaidl.IDataConnection/slot1":                     []string{"qcrildata.aidl_fuzzer"},
    "vendor.qti.hardware.data.connectionaidl.IDataConnection/slot2":                     []string{"qcrildata.aidl_fuzzer"},
    "vendor.qti.qccvndhal_aidl.IQccvndhal/qccvndhal":                                    []string{"qccvndhal.aidl_fuzzer"},
    "android.hardware.dumpstate.IDumpstateDevice/default":                                []string{"dumpstate.aidl_fuzzer"},
    "vendor.qti.qspmhal.IQspmhal/default":                                                []string{"qspmhal.aidl_fuzzer"},
    "vendor.qti.hardware.qseecom.IQSEECom/default":                                        EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.radio.qcrilhook.IQtiOemHook/oemhook0":                            EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.radio.qcrilhook.IQtiOemHook/oemhook1":                            EXCEPTION_NO_FUZZER,
    "android.hardware.camera.provider.ICameraProvider/vendor_qti/0":                       EXCEPTION_NO_FUZZER,
    "android.hardware.biometrics.fingerprint.IFingerprint/default":                        []string{"aidl_fuzzer_qfp_daemon"},
    "vendor.qti.hardware.fingerprint.IQfpExtendedFingerprint/default":                     []string{"aidl_fuzzer_qfp_daemon"},
    "android.hardware.light.ILights/default":                                              []string{"vendor.qti.hardware.lights-service.aidl_fuzzer"},
    "android.hardware.vibrator.IVibrator/default":                                         []string{"vendor.qti.hardware.vibrator-service.aidl_fuzzer"},
    "android.hardware.usb.IUsb/default":                                                   []string{"aidl_fuzz_usb_service"},
    "android.hardware.usb.gadget.IUsbGadget/default":                                      []string{"aidl_fuzz_usb_service"},
    "vendor.qti.qesdhalaidl.IQesdhal/default":                                             []string{"aidl_fuzzer_qesdk"},
    "vendor.qti.qesdsys.IQesdSys/default":                                                 []string{"aidl_fuzzer_qesdk"},
    "vendor.qti.hardware.alarm.IAlarm/default":                                            []string{"aidl_fuzzer_alarm_service"},
    "vendor.qti.hardware.debugutils.IDebugUtils/default":                                  []string{"aidl_fuzzer_debugutils"},
    "vendor.qti.hardware.servicetrackeraidl.IServicetracker/default":                      []string{"aidl_fuzzer_service_tracker"},
    "vendor.qti.hardware.radio.qtiradio.IQtiRadioStable/slot":                             EXCEPTION_NO_FUZZER,
    "android.hardware.radio.config.IRadioConfig/default":                                  []string{"aidl_fuzzer_radio_config"},
    "android.hardware.radio.messaging.IRadioMessaging/slot1":                              []string{"aidl_fuzzer_radio_messaging"},
    "android.hardware.radio.messaging.IRadioMessaging/slot2":                              []string{"aidl_fuzzer_radio_messaging"},
    "android.hardware.radio.modem.IRadioModem/slot1":                                      []string{"aidl_fuzzer_radio_modem"},
    "android.hardware.radio.modem.IRadioModem/slot2":                                      []string{"aidl_fuzzer_radio_modem"},
    "android.hardware.radio.network.IRadioNetwork/slot1":                                  []string{"aidl_fuzzer_radio_network"},
    "android.hardware.radio.sap.ISap/slot1":                                               []string{"aidl_fuzzer_radio_sap"},
    "android.hardware.radio.sap.ISap/slot2":                                               []string{"aidl_fuzzer_radio_sap"},
    "android.hardware.radio.sim.IRadioSim/slot1":                                          []string{"aidl_fuzzer_radio_sim"},
    "android.hardware.radio.sim.IRadioSim/slot2":                                          []string{"aidl_fuzzer_radio_sim"},
    "android.hardware.radio.voice.IRadioVoice/slot1":                                      []string{"aidl_fuzzer_radio_voice"},
    "android.hardware.radio.voice.IRadioVoice/slot2":                                      []string{"aidl_fuzzer_radio_voice"},
    "android.hardware.secure_element.ISecureElement/SIM1":                                 []string{"aidl_fuzzer_secure_lement"},
    "android.hardware.secure_element.ISecureElement/SIM2":                                 []string{"aidl_fuzzer_secure_lement"},
    "vendor.qti.hardware.radio.qtiradioconfig.IQtiRadioConfig/default":                    []string{"aidl_fuzzer_qti_radio_config"},
    "vendor.qti.hardware.radio.lpa.IUimLpa/UimLpa0":                                       []string{"aidl_fuzzer_radio_uimlpa"},
    "vendor.qti.hardware.radio.lpa.IUimLpa/UimLpa1":                                       []string{"aidl_fuzzer_radio_uimlpa"},
    "vendor.qti.hardware.radio.uim_remote_client.IUimRemoteServiceClient/uimRemoteClient0": []string{"aidl_fuzzer_radio_uim_remote_client"},
    "vendor.qti.hardware.radio.uim_remote_client.IUimRemoteServiceClient/uimRemoteClient1": []string{"aidl_fuzzer_radio_uim_remote_client"},
    "vendor.qti.hardware.radio.uim_remote_server.IUimRemoteServiceServer/uimRemoteServer0": []string{"aidl_fuzzer_radio_uim_remote_server"},
    "vendor.qti.hardware.radio.uim_remote_server.IUimRemoteServiceServer/uimRemoteServer1": []string{"aidl_fuzzer_radio_uim_remote_server"},
    "vendor.qti.hardware.radio.uim.IUim/Uim0":                                              []string{"aidl_fuzzer_radio_uim_service"},
    "vendor.qti.hardware.radio.uim.IUim/Uim1":                                              []string{"aidl_fuzzer_radio_uim_service"},
    "vendor.qti.hardware.radio.ims.IImsRadio/imsradio0":                                    EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.radio.ims.IImsRadio/imsradio1":                                    EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.radio.am.IQcRilAudio/slot1":                                       EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.radio.am.IQcRilAudio/slot2":                                       EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.radio.internal.deviceinfo.IDeviceInfo/deviceinfo":                 EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.radio.atfwd.IAtFwd/AtFwdAidl":                                     EXCEPTION_NO_FUZZER,
    "android.hardware.radio.data.IRadioData/slot1":                                         EXCEPTION_NO_FUZZER,
    "android.hardware.radio.data.IRadioData/slot2":                                         EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.data.connectionfactory.IFactory/slot0":                            EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.data.connectionfactory.IFactory/slot1":                            EXCEPTION_NO_FUZZER,
    "vendor.qti.ImsRtpService.IRTPService/ImsRtpService":                                   EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.embmssl.IEmbms/default":                                           EXCEPTION_NO_FUZZER,
    "android.hardware.graphics.allocator.IAllocator/default":                               []string{"aidl_fuzzer_display_gralloc"},
    "vendor.qti.hardware.qconfig.IQConfig/default":                                         EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.vpp.IVppService/default":                                          EXCEPTION_NO_FUZZER,
    "android.hardware.identity.IIdentityCredentialStore/default":                           EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.trustedui.ITrustedInput/default":                                  EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.trustedui.ITrustedUI/default":                                     EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.qteeconnector.IAppConnector/default":                              EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.qteeconnector.IGPAppConnector/default":                            EXCEPTION_NO_FUZZER,
    "android.hardware.secure_element.ISecureElement/eSE1":                                  EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.secureprocessor.device.ISecureProcessor/qti-tee":                  EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.secureprocessor.device.ISecureProcessor/qti-tvm":                  EXCEPTION_NO_FUZZER,
    "android.hardware.security.keymint.IKeyMintDevice/default":                             EXCEPTION_NO_FUZZER,
    "android.hardware.security.keymint.IKeyMintDevice/strongbox":                           EXCEPTION_NO_FUZZER,
    "android.hardware.security.keymint.IRemotelyProvisionedComponent/default":              EXCEPTION_NO_FUZZER,
    "android.hardware.security.keymint.IRemotelyProvisionedComponent/strongbox":            EXCEPTION_NO_FUZZER,
    "android.service.gatekeeper.IGateKeeperService":                                        EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.sensorscalibrate.ISensorsCalibrate/default":                       []string{"aidl_fuzzer_sensors_calibrate"},
    "vendor.qti.hardware.bttpi.IBtTpi/default":                                             EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.bluetooth.xpanprovider.IXpanProvider/default":                     EXCEPTION_NO_FUZZER,
    "android.hardware.boot.IBootControl/default":                                           []string{"aidl_fuzzer_bootctrl"},
    "android.hardware.gnss.IGnss/default":                                                  EXCEPTION_NO_FUZZER, 
    "android.hardware.drm.IDrmFactory/wfdhdcp":                                             EXCEPTION_NO_FUZZER,
    "android.hardware.power.IPower/default":                                                EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.bluetooth.gatt.IBluetoothGatt/default":                            []string{"vendor.qti.hardware.bluetooth.gatt-aidl_fuzzer"},
    "android.hardware.gatekeeper.IGatekeeper/default":                                      EXCEPTION_NO_FUZZER,
    "android.hardware.security.secureclock.ISecureClock/default":                           EXCEPTION_NO_FUZZER,
    "android.hardware.security.sharedsecret.ISharedSecret/default":                         EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.spu.ISPUManager/default":                                          []string{"aidl_fuzzer_spu_service"},
    "vendor.qti.hardware.qxr.IQXRAudioService/default":                                     EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.qxr.IQXRSplitService/default":                                     EXCEPTION_NO_FUZZER,
    "android.hardware.tetheroffload.IOffload/default":                                      []string{"aidl_fuzzer_ipacm"},
    "android.hardware.thermal.IThermal/default":                                            []string{"aidl_fuzzer_thermal"},
    "android.hardware.bluetooth.audio.IBluetoothAudioProviderFactory/default":              []string{"android.bluetooth.audio-aidl_fuzzer"},
    "vendor.qti.hardware.ListenSoundModelAidl.IListenSoundModel/default":                   EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.qspa.IQspa/default":                                               []string{"vendor.qti.qspa-service.aidl_fuzzer"},
    "vendor.qti.hardware.display.aiqe.IDisplayAiqe/default":                                []string{"displayconfig.aidl_fuzzer"},
    "vendor.qti.hardware.display.config.IDisplayConfig/default":                            []string{"displayconfig.aidl_fuzzer"},
    "android.hardware.graphics.composer3.IComposer/default":                                []string{"displayconfig.aidl_fuzzer"},
    "vendor.qti.hardware.display.color/IDisplayColor/default":                              []string{"displayconfig.aidl_fuzzer"},
    "vendor.qti.hardware.display.postproc.IDisplayPostproc/default":                        []string{"displayconfig.aidl_fuzzer"},
    "vendor.qti.data.qmsservice.IQmsService":                                               EXCEPTION_NO_FUZZER,
    "vendor.qti.data.dmapconsent.IService/default":                                         EXCEPTION_NO_FUZZER,
    "android.hardware.audio.core.IModule/default":                                          EXCEPTION_NO_FUZZER,
    "android.hardware.audio.core.IModule/r_submix":                                         EXCEPTION_NO_FUZZER,
    "android.hardware.audio.core.IModule/usb":                                              EXCEPTION_NO_FUZZER,
    "android.hardware.audio.core.IConfig/default":                                          EXCEPTION_NO_FUZZER,
    "vendor_npu_monitor_observer":                                                          []string{"vendor_npu_monitor_observer_fuzzer"},
    "vendor.qti.AvfQcvmManager.IAvfQcvmManager/default":                                    EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.display.snapallocext.ISnapAllocExt/default":                       []string{"aidl_fuzzer_display_gralloc"},
    "vendor.qti.hardware.camera.postproc.IPostProcService/camerapostprocservice":           EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.powerstateservice.IPowerStateService/default":                     EXCEPTION_NO_FUZZER,
    "vendor.qti.hardware.powerstateservice.IPowerStateUtility/default":                     EXCEPTION_NO_FUZZER,
 }
)
